### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
Ping @ljod @jhlegarreta @pieper @zhangfanmark

After addressing:
* https://github.com/SlicerDMRI/SlicerWMA-OLD/issues/11

... it would be great if this could be updated & integrated :pray:

**Comment by pieper** [comment]
Thanks for the ping @jcfr - I believe the old SlicerWMA was the actually slicer extension, while whitematteranalysis was the repo with more general non-slicer functionality, so changing the URL like this doesn't look right.  

@zhangfanmark was working on the new extension here: https://github.com/SlicerDMRI/SlicerTractParcellation

This is the work in progress for the new extension: https://github.com/Slicer/ExtensionsIndex/pull/2037

Maybe we should remove the old extension index entry until the new extension is ready?

**Comment by jcfr** [comment]
Ditto. The file has been fixed. I then suggest to rename `SlicerWMA-OLD` back to `SlicerWMA` and archive it as detailed in #11 

Once `SlicerTractParcellation` is ready, we will then also archive[^1] the `SlicerWMA` extension.

[^1]: https://github.com/Slicer/ExtensionsIndex/tree/main/ARCHIVE#archive

**Comment by jcfr** [comment]
Please, could this be approved & merged :pray: 

The changes are only related to using `https` instead of `http`, and removing the use of an invalid screenshot URL.

cc: @ljod @jhlegarreta @pieper @zhangfanmark

**Review by pieper — APPROVED** [review]
Thanks @jcfr 👍

**Pull request merged**
